version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "eu-north-1"
    IMAGE_REPO_NAME: "mlops"
    IMAGE_TAG: "latest"

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - make install

  pre_build:
    commands:
      - echo "Running lint and format check..."
      - make lint
      - black --check *.py
      - echo "Running tests..."
      - make test
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 568256617374.dkr.ecr.eu-north-1.amazonaws.com

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG 568256617374.dkr.ecr.eu-north-1.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push 568256617374.dkr.ecr.eu-north-1.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo "Docker image pushed successfully!"